name: Build & Deploy to Render

on:
  push:
    branches: [main] # or your active branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image from mindstate_AI/
        run: docker build -t mental-health-app ./mindstate_AI

      - name: Trigger Render Deploy Hook
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
